releasetools: completely remove downgrade support
Was initially removed from https://github.com/CandyRoms/build/commit/d66d6bab89af1c814979ebbc27d3ec929ea30131
but that left some problems since it was incomplete.

Traceback (most recent call last):
  File "./build/tools/releasetools/ota_from_target_files", line 2164, in <module>
    main(sys.argv[1:])
  File "./build/tools/releasetools/ota_from_target_files", line 2019, in main
    if OPTIONS.downgrade:
AttributeError: 'Options' object has no attribute 'downgrade'

Change-Id: I1a606c0d6baa20abfa224e44f2292502ce437f0a